/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a room
         * @description Creates an open room and returns its opaque application ID together
         *     with the invite URL. The LiveKit room is created later, when the first
         *     participant connects.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{inviteCode}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A case-sensitive, cryptographically random 32-character code using
                 *     ASCII letters and digits (A-Z, a-z, 0-9). The backend stores only its
                 *     SHA-256 hash. Legacy 43-character codes are not supported.
                 */
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        /**
         * Get public room status
         * @description Returns the application-level room status. Participant information and
         *     the internal LiveKit room name are never exposed.
         */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{inviteCode}/join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A case-sensitive, cryptographically random 32-character code using
                 *     ASCII letters and digits (A-Z, a-z, 0-9). The backend stores only its
                 *     SHA-256 hash. Legacy 43-character codes are not supported.
                 */
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a room
         * @description Validates the room and display name, then issues short-lived LiveKit
         *     connection credentials. Duplicate display names are allowed. Local
         *     microphone availability and browser permission are not prerequisites:
         *     the participant may connect without publishing an audio track and
         *     start publishing a microphone later with the same credentials.
         */
        post: operations["joinRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/livekit/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a LiveKit webhook
         * @description Receives and verifies LiveKit webhook events. Unsupported authenticated
         *     event types are acknowledged and ignored. Duplicate event IDs are
         *     handled idempotently.
         */
        post: operations["receiveLiveKitWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRoomResponse: {
            /**
             * @description Opaque application-level room ID. It is not an invite code, is not
             *     shown as the room title, and must not be used to construct the
             *     share URL.
             */
            roomId: string;
            /**
             * Format: uri-reference
             * @description Same-origin `/rooms/{inviteCode}` URL. The frontend resolves it to
             *     an absolute URL before sharing and may copy the current browser URL
             *     after navigation. The backend stores only the invite-code hash and
             *     does not provide a separate endpoint for reconstructing this URL.
             * @example /rooms/w7pM8xK2qR5vT9nY4dF6gH1jL3sC0bN2
             */
            inviteUrl: string;
            /**
             * Format: date-time
             * @description Time by which the first participant must join.
             */
            expiresAt: string;
            /** @constant */
            maxParticipants: 8;
        };
        RoomResponse: {
            status: components["schemas"]["RoomStatus"];
            /**
             * Format: date-time
             * @description Original deadline for the first participant to join.
             */
            expiresAt: string;
        };
        /** @enum {string} */
        RoomStatus: "open" | "active" | "finished" | "expired";
        /**
         * @description The backend does not receive microphone availability or permission
         *     state. The same request is used for participants joining with or without
         *     a local microphone track.
         */
        JoinRoomRequest: {
            /**
             * @description Participant-visible name. Whitespace is trimmed before validation;
             *     the resulting value must contain from 1 to 32 Unicode characters.
             */
            displayName: string;
        };
        JoinRoomResponse: {
            /**
             * Format: uri
             * @description LiveKit WebSocket URL.
             * @example wss://radio96.example.livekit.cloud
             */
            serverUrl: string;
            /**
             * @description Short-lived LiveKit participant JWT. It permits microphone-only
             *     publication but does not require the participant to publish a track.
             */
            participantToken: string;
            /** @description Opaque identity unique within the LiveKit room. */
            participantIdentity: string;
        };
        LiveKitWebhookEvent: {
            /**
             * Format: uuid
             * @description Stable event identifier used for idempotency.
             */
            id: string;
            /**
             * Format: int64
             * @description Unix timestamp in seconds.
             */
            createdAt: number;
            /** @example room_started */
            event: string;
            room?: components["schemas"]["LiveKitRoom"];
        } & {
            [key: string]: unknown;
        };
        LiveKitRoom: {
            sid?: string;
            name?: string;
        } & {
            [key: string]: unknown;
        };
        Error: {
            /**
             * @description Stable machine-readable error code.
             * @example invalid_name
             * @example room_not_found
             * @example room_expired
             * @example room_finished
             * @example room_full
             * @example media_unavailable
             * @example invalid_webhook
             * @example internal_error
             */
            code: string;
            /** @description Human-readable message; clients must branch on code. */
            message: string;
        };
    };
    responses: {
        /** @description Request failed */
        ErrorResponse: {
            headers: {
                "Cache-Control": components["headers"]["CacheControl"];
                "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description A case-sensitive, cryptographically random 32-character code using
         *     ASCII letters and digits (A-Z, a-z, 0-9). The backend stores only its
         *     SHA-256 hash. Legacy 43-character codes are not supported.
         */
        InviteCode: string;
    };
    requestBodies: never;
    headers: {
        /** @description Prevents storage of room links and participant credentials. */
        CacheControl: "no-store";
        /** @description Prevents an invite code from leaking through the Referer header. */
        ReferrerPolicy: "no-referrer";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room created */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoomResponse"];
                };
            };
            500: components["responses"]["ErrorResponse"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A case-sensitive, cryptographically random 32-character code using
                 *     ASCII letters and digits (A-Z, a-z, 0-9). The backend stores only its
                 *     SHA-256 hash. Legacy 43-character codes are not supported.
                 */
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room status */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            404: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    joinRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description A case-sensitive, cryptographically random 32-character code using
                 *     ASCII letters and digits (A-Z, a-z, 0-9). The backend stores only its
                 *     SHA-256 hash. Legacy 43-character codes are not supported.
                 */
                inviteCode: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRoomRequest"];
            };
        };
        responses: {
            /** @description LiveKit connection credentials */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    "Referrer-Policy": components["headers"]["ReferrerPolicy"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRoomResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            410: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
            503: components["responses"]["ErrorResponse"];
        };
    };
    receiveLiveKitWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/webhook+json": components["schemas"]["LiveKitWebhookEvent"];
            };
        };
        responses: {
            /** @description Event accepted, already processed, or intentionally ignored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
}
