// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireRoomByName = `-- name: ExpireRoomByName :execrows
UPDATE rooms
SET status = 'expired'
WHERE name = $1
  AND status = 'open'
  AND expires_at <= $2::timestamptz
`

type ExpireRoomByNameParams struct {
	Name string             `db:"name"`
	Now  pgtype.Timestamptz `db:"now"`
}

func (q *Queries) ExpireRoomByName(ctx context.Context, arg ExpireRoomByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireRoomByName, arg.Name, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findLifecycleCandidates = `-- name: FindLifecycleCandidates :many
SELECT name, status, expires_at, last_empty_at
FROM rooms
WHERE status IN ('open', 'active')
   OR (status = 'expired' AND expires_at >= $1::timestamptz - interval '10 minutes')
ORDER BY created_at, name
`

type FindLifecycleCandidatesRow struct {
	Name        string             `db:"name"`
	Status      string             `db:"status"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at"`
	LastEmptyAt pgtype.Timestamptz `db:"last_empty_at"`
}

func (q *Queries) FindLifecycleCandidates(ctx context.Context, now pgtype.Timestamptz) ([]FindLifecycleCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findLifecycleCandidates, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindLifecycleCandidatesRow{}
	for rows.Next() {
		var i FindLifecycleCandidatesRow
		if err := rows.Scan(
			&i.Name,
			&i.Status,
			&i.ExpiresAt,
			&i.LastEmptyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishIdleRoomByName = `-- name: FinishIdleRoomByName :execrows
UPDATE rooms
SET status = 'finished',
    finished_at = GREATEST(started_at, $1::timestamptz)
WHERE name = $2
  AND status = 'active'
  AND last_empty_at <= $1::timestamptz - interval '10 minutes'
`

type FinishIdleRoomByNameParams struct {
	Now  pgtype.Timestamptz `db:"now"`
	Name string             `db:"name"`
}

func (q *Queries) FinishIdleRoomByName(ctx context.Context, arg FinishIdleRoomByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIdleRoomByName, arg.Now, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRoomEmptyByName = `-- name: MarkRoomEmptyByName :execrows
UPDATE rooms
SET last_empty_at = COALESCE(last_empty_at, GREATEST(started_at, $1::timestamptz))
WHERE name = $2
  AND status = 'active'
`

type MarkRoomEmptyByNameParams struct {
	EmptyAt pgtype.Timestamptz `db:"empty_at"`
	Name    string             `db:"name"`
}

func (q *Queries) MarkRoomEmptyByName(ctx context.Context, arg MarkRoomEmptyByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRoomEmptyByName, arg.EmptyAt, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWebhookEvent = `-- name: RecordWebhookEvent :execrows
INSERT INTO webhook_events (id, room_name, event_type, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type RecordWebhookEventParams struct {
	ID        string             `db:"id"`
	RoomName  string             `db:"room_name"`
	EventType string             `db:"event_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) RecordWebhookEvent(ctx context.Context, arg RecordWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWebhookEvent,
		arg.ID,
		arg.RoomName,
		arg.EventType,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startRoomByName = `-- name: StartRoomByName :execrows
UPDATE rooms
SET status = 'active',
    started_at = COALESCE(started_at, GREATEST(created_at, $1::timestamptz)),
    last_empty_at = NULL
WHERE name = $2
  AND status IN ('open', 'expired', 'active')
`

type StartRoomByNameParams struct {
	StartedAt pgtype.Timestamptz `db:"started_at"`
	Name      string             `db:"name"`
}

func (q *Queries) StartRoomByName(ctx context.Context, arg StartRoomByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, startRoomByName, arg.StartedAt, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
