// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID             string             `db:"id"`
	InviteCodeHash []byte             `db:"invite_code_hash"`
	Name           string             `db:"name"`
	Status         string             `db:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at"`
	StartedAt      pgtype.Timestamptz `db:"started_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at"`
}
