// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (
    id,
    invite_code_hash,
    name,
    status,
    created_at,
    expires_at,
    started_at,
    finished_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateRoomParams struct {
	ID             string             `db:"id"`
	InviteCodeHash []byte             `db:"invite_code_hash"`
	Name           string             `db:"name"`
	Status         string             `db:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at"`
	StartedAt      pgtype.Timestamptz `db:"started_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom,
		arg.ID,
		arg.InviteCodeHash,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const findRoomByInviteCodeHash = `-- name: FindRoomByInviteCodeHash :one
SELECT
    id,
    name,
    status,
    created_at,
    expires_at,
    started_at,
    finished_at
FROM rooms
WHERE invite_code_hash = $1
LIMIT 1
`

type FindRoomByInviteCodeHashRow struct {
	ID         string             `db:"id"`
	Name       string             `db:"name"`
	Status     string             `db:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	StartedAt  pgtype.Timestamptz `db:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at"`
}

func (q *Queries) FindRoomByInviteCodeHash(ctx context.Context, inviteCodeHash []byte) (FindRoomByInviteCodeHashRow, error) {
	row := q.db.QueryRow(ctx, findRoomByInviteCodeHash, inviteCodeHash)
	var i FindRoomByInviteCodeHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :execrows
UPDATE rooms
SET
    status = $1,
    started_at = $2,
    finished_at = $3
WHERE id = $4
  AND (
      status = $1
      OR (status = 'open' AND $1::TEXT IN ('active', 'expired'))
      OR (status = 'active' AND $1::TEXT = 'finished')
  )
`

type UpdateRoomParams struct {
	Status     string             `db:"status"`
	StartedAt  pgtype.Timestamptz `db:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at"`
	ID         string             `db:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoom,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
